version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'Mari'
      MYSQL_PASSWORD: 'Mari123'
      MYSQL_ROOT_PASSWORD: 'Mari123'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - user:/var/lib/mysql
  # Names our volume
volumes:
   user: